<a href="https://colab.research.google.com/github/jayasriponali/masai/blob/main/Assessment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip3 install pandas
!pip3 install numpy

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (2.0.2)

In [2]:
import pandas as pd

import numpy as np

In [3]:

data = {
    'order_id':        [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    'customer_city':   ['Mumbai', 'Delhi', 'Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Pune', 'Delhi', 'Mumbai', 'Pune'],
    'cuisine_type':    ['Italian', 'Chinese', 'Italian', 'Indian', 'Chinese', 'Indian', 'Italian', 'Indian', 'Chinese', 'Italian'],
    'delivery_time':   [30, 45, None, 50, 40, 35, None, 55, 42, 38],
    'order_amount':    [250, 400, 300, 150, 500, 200, 350, 450, None, 275],
    'is_delivered':    [True, True, False, True, True, True, False, True, True, True]
}

##Task 1

In [5]:
df = pd.DataFrame(data)
df

,order_id,customer_city,cuisine_type,delivery_time,order_amount,is_delivered
0,101,Mumbai,Italian,30.0,250.0,True
1,102,Delhi,Chinese,45.0,400.0,True
2,103,Mumbai,Italian,NaN,300.0,False
3,104,Pune,Indian,50.0,150.0,True
4,105,Delhi,Chinese,40.0,500.0,True
5,106,Mumbai,Indian,35.0,200.0,True
6,107,Pune,Italian,NaN,350.0,False
7,108,Delhi,Indian,55.0,450.0,True
8,109,Mumbai,Chinese,42.0,NaN,True
9,110,Pune,Italian,38.0,275.0,True

In [6]:
df.shape

(10, 6)

In [8]:
type(df)

pandas.core.frame.DataFrame

In [9]:
df.isnull().sum()

order_id         0
customer_city    0
cuisine_type     0
delivery_time    2
order_amount     1
is_delivered     0
dtype: int64

##Task2

In [11]:
df.describe()

        order_id  delivery_time  order_amount
count   10.00000        8.00000      9.000000
mean   105.50000       41.87500    319.444444
std      3.02765        8.06115    115.770367
min    101.00000       30.00000    150.000000
25%    103.25000       37.25000    250.000000
50%    105.50000       41.00000    300.000000
75%    107.75000       46.25000    400.000000
max    110.00000       55.00000    500.000000

In [16]:
df['delivery_time'].median()

41.0

In [17]:
df['order_amount'].mean()

np.float64(319.44444444444446)

##Task4

In [29]:
array = df.loc[:,'order_amount']
print(array)

0    250.0
1    400.0
2    300.0
3    150.0
4    500.0
5    200.0
6    350.0
7    450.0
8      NaN
9    275.0
Name: order_amount, dtype: float64

In [31]:
mean_array = np.mean(array)
print(mean_array)

319.44444444444446

In [36]:
std_array = np.std(array)
print(std_array)

109.14934835771389

In [33]:
max_a = np.max(array)
print(max_a)

500.0

In [34]:
min_a = np.min(array)
print(min_a)

150.0